### ISSUE TITLE
soft_delete condition can't applied to count() ？

### ISSUE THREAD

**Issue by nobject** [go-gorm/soft_delete#16]
## Description

when i call  count()
`db.WithContext(ctx).Table(p.TableName()).Debug().Count(&total)`
debug the sql output:
`SELECT count(*) FROM project`
the deleted_at where condition is not append it.

when I call find(), it will auto append

Is this a bug or is the design just like that?

**Comment by shushenghong** [comment]
try `db.Model` instead of `db.Table`

**Comment by nobject** [comment]
> try `db.Model` instead of `db.Table`

it works, thank you!
