### ISSUE TITLE
Different curTime with gorm.DeletedAt

### ISSUE THREAD

**Issue by mylifeafterthat** [go-gorm/soft_delete#2]
## Why using different gorm.DeletedAt

See code in line https://github.com/go-gorm/gorm/blob/master/soft_delete.go#L108
And https://github.com/go-gorm/soft_delete/blob/master/soft_delete.go#L91

## The document you expected this should be explained

I have some issues using this plugin with mysql, i got `Error 1292: Incorrect datetime value: '1618374894' for column 'deleted_at' at row 2`.

It because mysql rejected format

```sql
UPDATE `user` SET `is_deleted`=1,`deleted_at`=1618374894 
WHERE uid IN ('c1q18tjlmtapueo48tr0','c1r6jln2hraij33e5t90','c1r6ql72hraitu6jb5dg','c1r6rln2hraitu6jb5fg','c1r6vq72hraj37cr5p50') 
AND `user`.`is_deleted` = 0
```

## Expected answer

Why dont you use same format like gorm.DeletedAt?

**Comment by jinzhu** [comment]
the plugin uses `int` as the data type, you should use the default `gorm.DeletedAt` one if using `time.Time`

**Comment by mylifeafterthat** [comment]
sorry, do you have example?

i try models like this

```go
type User struct {
  UID        string
  Name      string
  DeletedAt gorm.DeletedAt
  IsDeleted     soft_delete.DeletedAt `gorm:"softDelete:flag,DeletedAtField:DeletedAt"`
}

result := p.gorm.WithContext(ctx).Where("uid IN ?", uids).Delete(&User{})
```
if I'm using schema User like that, is_deleted set to 0 and deleted_at  set to 2021-04-14 05:43:06

then I'm trying to switch DeletedAt and IsDeleted

```go
type User struct {
  UID        string
  Name      string
  IsDeleted     soft_delete.DeletedAt `gorm:"softDelete:flag,DeletedAtField:DeletedAt"`
  DeletedAt gorm.DeletedAt
}
```

i got error Error 1292: Incorrect datetime value: '1618379369' for column 'deleted_at' at row 8.
If i change gorm.DeletedAt to time.Time, i got same error

in my case, i need both, flag and timestamp. flag is_deleted for indexing.

so what do you mean `you should use the default gorm.DeletedAt one if using time.Time`
