### ISSUE TITLE
Insert error when using 3rd way (Both DeletedAt and IsDel)

### ISSUE THREAD

**Issue by lichi0206** [go-gorm/soft_delete#5]
## Your Question

When I using the 3rd way which contains both "DeletedAt" and "IsDel" column, I will get error when execute insert action.

model struct like:
type Model struct {
...
        DeletedAt time.Time
	IsDel soft_delete.DeletedAt `gorm:"softDelete:flag,DeletedAtField:DeletedAt"`
...
}

and when I call insert statement, I got error like that:

GORM LOG INSERT INTO `test` (`created_at`,`updated_at`,`deleted_at`,`is_del`) VALUES ('2021-07-06 12:01:04','2021-08-02 11:19:45.933','0000-00-00 00:00:00','0'), Error: Error 1292: Incorrect datetime value: '0000-00-00' for column 'deleted_at' at row 1

In Mysql DB, the "deleted_at" column is set to "datetime", and "is_del" is set to "int unsigned"

I guess when I set the "DeletedAtField" tag, it will auto set "DeletedAt" to "0000-00-00 00:00:00", but how do I fix this issue? is there any other tag or should I use gorm default value to solve this?

**Comment by jinzhu** [comment]
use `DeletedAt *time.Time`
